basePath: /
definitions:
  store.Site:
    properties:
      id:
        type: integer
      location:
        type: string
      name:
        type: string
      status:
        type: boolean
    type: object
host: localhost:7072
info:
  contact:
    email: parameswaribala@gmail.com
    name: API Support
  description: This is api service for managing Sites
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Site API
  version: "1.0"
paths:
  /sites/v1.0:
    get:
      consumes:
      - application/json
      description: Returns list of sites
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/store.Site'
            type: array
      summary: Get all sites
      tags:
      - sites
    post:
      consumes:
      - application/json
      description: Adds a new site
      parameters:
      - description: Site to create
        in: body
        name: site
        required: true
        schema:
          $ref: '#/definitions/store.Site'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/store.Site'
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new site
      tags:
      - sites
    put:
      consumes:
      - application/json
      description: Update existing site with the input payload
      parameters:
      - description: Update site
        in: body
        name: site
        required: true
        schema:
          $ref: '#/definitions/store.Site'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/store.Site'
      summary: Update existing site
      tags:
      - sites
  /sites/v1.0/{id}:
    delete:
      consumes:
      - application/json
      description: Delete requested site
      parameters:
      - description: ID of the Site
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/store.Site'
        "400":
          description: Invalid ID supplied
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Site not found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete requested site
      tags:
      - sites
    get:
      consumes:
      - application/json
      description: Get details of requestesd site
      parameters:
      - description: ID of the Site
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/store.Site'
        "400":
          description: Invalid ID supplied
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Site not found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get details of requested site
      tags:
      - sites
swagger: "2.0"
